image: node:latest

stages:
  - install
  - test

cache: 
  paths:
    - node_modules/

before_script:
  - npm install

install: 
  stage: install
  script: 
    - npm ci
  artifacts:
    paths:
      - node_modules/

test:
  image: cypress/included:13.7.1
  stage: test
  script: 
    - npm run test